import { LabProgress } from "./LabProgress";
import { siteHref } from "../lib/site-path";

export function M1PreLab() {
  return <>
    <section className="content-section first-section"><span className="content-kicker">BEFORE YOU CODE</span><h2>The investigation in one sentence</h2><p className="lead-text">Can a quantum kernel create a useful similarity space for malware families after high-dimensional behavioral features are compressed to a small number of qubits—and how does that result compare with a strong classical SVM?</p><div className="time-callout"><strong>Recommended time</strong><span>45-60 minutes</span><span>No quantum background assumed</span></div></section>
    <section className="content-section"><span className="content-kicker">PART 1 · CYBERSECURITY CONTEXT</span><h2>Malware families share behavior, not just names</h2><div className="two-column-copy"><div><p>A malware family groups malicious programs that share code, behavior, infrastructure, or lineage. Classification helps analysts connect a new sample to known tactics, prioritize threats, and choose appropriate containment or remediation.</p><p>This module uses dynamic CAPA-style behavioral features. Rather than executing malware yourself, you work with a prepared table that records capabilities observed from samples. Never upload real malware binaries to Colab.</p></div><div className="concept-card"><small>EXAMPLE BEHAVIOR SIGNALS</small><ul><li>Process and thread manipulation</li><li>Network communication</li><li>File-system operations</li><li>Persistence mechanisms</li><li>Cryptographic or packing behavior</li></ul></div></div></section>
    <section className="content-section"><span className="content-kicker">PART 2 · CLASSICAL FOUNDATION</span><h2>Why start with an SVM?</h2><p className="lead-text small">A support vector machine searches for a decision boundary with the widest useful margin. A kernel lets it reason about nonlinear structure by comparing samples in another feature space.</p><div className="kernel-visual"><div><span>x</span><small>malware sample</small></div><b>→</b><div><span>ϕ(x)</span><small>feature mapping</small></div><b>→</b><div><span>K(x,y)</span><small>similarity</small></div><b>→</b><div><span>ŷ</span><small>family label</small></div></div><div className="definition-grid"><article><small>FEATURE VECTOR</small><p>A numeric description of one malware sample.</p></article><article><small>KERNEL</small><p>A similarity function used by an SVM without explicitly building every mapped feature.</p></article><article><small>BASELINE</small><p>A credible classical model that tells us whether a quantum result is actually informative.</p></article></div></section>
    <section className="content-section"><span className="content-kicker">PART 3 · QUANTUM KERNEL</span><h2>Move the similarity calculation into quantum state space</h2><div className="equation-card"><span>K(x,y)</span><strong>= |⟨ϕ(x) | ϕ(y)⟩|²</strong><p>The fidelity kernel measures the squared overlap between quantum states prepared from two classical feature vectors.</p></div><div className="step-explainer"><article><span>01</span><div><h3>Reduce</h3><p>PCA compresses the classical feature space to the number of available qubits.</p></div></article><article><span>02</span><div><h3>Scale</h3><p>Each reduced feature is mapped to an angle from 0 to π.</p></div></article><article><span>03</span><div><h3>Encode</h3><p>ZZFeatureMap uses rotations and entangling operations to prepare |ϕ(x)⟩.</p></div></article><article><span>04</span><div><h3>Compare</h3><p>FidelityQuantumKernel computes pairwise state overlaps for QSVC.</p></div></article></div></section>
    <section className="content-section"><span className="content-kicker">CLASSICAL VS. QUANTUM</span><h2>Same classification goal, different kernel</h2><div className="comparison-table" role="table"><div className="table-row table-head" role="row"><span>Question</span><span>Classical RBF-SVM</span><span>QSVC</span></div><div className="table-row" role="row"><strong>Similarity</strong><span>RBF kernel in classical feature space</span><span>Fidelity between encoded quantum states</span></div><div className="table-row" role="row"><strong>Data preparation</strong><span>Scaling is usually enough</span><span>Scaling plus severe dimension reduction</span></div><div className="table-row" role="row"><strong>Compute cost</strong><span>Efficient for this small lab</span><span>Pairwise circuits grow quickly with sample count</span></div><div className="table-row" role="row"><strong>Interpretation</strong><span>Established baseline</span><span>Experimental comparison, not proof of advantage</span></div></div></section>
    <section className="content-section"><span className="content-kicker">READINESS CHECK</span><h2>Can you explain these before opening Colab?</h2><div className="knowledge-check"><details><summary>1. Why do we reduce the dataset to N_QUBITS features?</summary><p>The feature map needs one encoded value per qubit in this workflow. PCA creates a compact representation with exactly that dimension.</p></details><details><summary>2. Why do we train a classical SVM first?</summary><p>A baseline provides context. A QSVC accuracy by itself cannot show whether the quantum kernel is useful.</p></details><details><summary>3. What does a large kernel value mean?</summary><p>The two encoded states have high fidelity, so the quantum feature map treats the samples as similar.</p></details><details><summary>4. Does higher QSVC accuracy prove quantum advantage?</summary><p>No. The experiment is small, simulator-based, and sensitive to data selection and preprocessing. Evidence of advantage requires careful scaling, resource, statistical, and hardware analysis.</p></details></div><div className="next-stage"><div><strong>Ready?</strong><p>Keep this page open as a reference while you work.</p></div><a className="button button-primary" href={siteHref("/modules/m1/hands-on-lab")}>Continue to Hands-on Lab →</a></div></section>
  </>;
}

const Code = ({text}:{text:string}) => <pre className="code-block"><code>{text}</code></pre>;

export function M1HandsOn() {
  return <>
    <section className="lab-launch"><div><span className="content-kicker light">GOOGLE COLAB LAB</span><h2>Build a QSVM malware family classifier</h2><p>Run the supplied notebook from top to bottom on a simulator, record the checkpoints, and compare its quantum kernel with a classical RBF kernel.</p><div className="launch-buttons"><a className="button button-light" href={siteHref("/downloads/QSVM_Malware_Family_Classification.ipynb")} download>Download notebook ↓</a><a className="button button-outline-light" href="https://colab.research.google.com/" target="_blank" rel="noreferrer">Open Google Colab ↗</a></div><small>In Colab, choose File → Upload notebook, then select the downloaded .ipynb file.</small></div><div className="launch-spec"><span><small>ESTIMATED</small><strong>90-150 min</strong></span><span><small>RUNTIME</small><strong>CPU / Simulator</strong></span><span><small>CORE STACK</small><strong>Qiskit ML + scikit-learn</strong></span></div></section>
    <div className="lab-layout"><div className="lab-main">
      <section className="lab-step"><div className="step-marker"><span>01</span><i /></div><div><span className="content-kicker">ENVIRONMENT</span><h2>Install the scientific stack</h2><p>Run the installation cell once. If Colab asks you to restart the runtime, restart and resume with the imports.</p><Code text={'!pip -q install qiskit qiskit-machine-learning scikit-learn pandas matplotlib seaborn'} /><div className="checkpoint"><strong>Checkpoint 1</strong><p>The cell finishes without a red error. Record the installed qiskit-machine-learning version for reproducibility.</p></div></div></section>
      <section className="lab-step"><div className="step-marker"><span>02</span><i /></div><div><span className="content-kicker">DATA</span><h2>Upload, extract, and inspect</h2><p>Upload the instructor-provided <code>Dynamic Data for Malware Family Classification.zip</code>. The notebook searches the archive for <code>Dynamic_Capa_Feature_Space.csv</code>.</p><div className="safety-note"><strong>Safe lab rule</strong><p>Use only the prepared feature archive. Do not download, upload, or execute live malware binaries.</p></div><Code text={'from google.colab import files\nuploaded = files.upload()\n# The notebook extracts the first uploaded .zip and lists its CSV files.'} /><div className="checkpoint"><strong>Checkpoint 2</strong><p>Capture the dataframe shape, the label-column name, and the five most frequent malware families.</p></div></div></section>
      <section className="lab-step"><div className="step-marker"><span>03</span><i /></div><div><span className="content-kicker">EXPERIMENT CONTROL</span><h2>Start small and balanced</h2><p>Quantum kernel cost grows with pairwise comparisons. The default configuration creates an interpretable first run.</p><Code text={'TOP_N_CLASSES = 3\nSAMPLES_PER_CLASS = 25\nN_QUBITS = 4\nTEST_SIZE = 0.30\nRANDOM_STATE = 42'} /><div className="parameter-grid"><article><strong>3</strong><span>families</span></article><article><strong>75</strong><span>total samples</span></article><article><strong>4</strong><span>quantum features</span></article><article><strong>30%</strong><span>test split</span></article></div></div></section>
      <section className="lab-step"><div className="step-marker"><span>04</span><i /></div><div><span className="content-kicker">PREPROCESSING</span><h2>Create quantum-ready features without leakage</h2><p>Remove labels and metadata, discard zero-variance columns, split the data, then fit each transformation on the training set only.</p><ol className="numbered-list"><li><strong>VarianceThreshold</strong><span>removes columns that cannot separate samples.</span></li><li><strong>StandardScaler</strong><span>centers features before PCA.</span></li><li><strong>PCA</strong><span>reduces dimension to N_QUBITS.</span></li><li><strong>MinMaxScaler</strong><span>maps the reduced values to [0, π].</span></li></ol><div className="checkpoint"><strong>Checkpoint 3</strong><p>Report the original feature count, post-filter count, total PCA explained variance, and final train/test shapes.</p></div></div></section>
      <section className="lab-step"><div className="step-marker"><span>05</span><i /></div><div><span className="content-kicker">BASELINE</span><h2>Train the classical RBF-SVM first</h2><Code text={'classical_svm = SVC(kernel="rbf", C=1.0, gamma="scale")\nclassical_svm.fit(X_train_q, y_train)\ny_pred_classical = classical_svm.predict(X_test_q)'} /><p>Save its accuracy, per-class precision/recall/F1, and confusion matrix. This is the evidence your quantum model must be compared against.</p></div></section>
      <section className="lab-step feature-step"><div className="step-marker"><span>06</span><i /></div><div><span className="content-kicker">QUANTUM KERNEL</span><h2>Construct ZZFeatureMap + FidelityQuantumKernel</h2><Code text={'feature_map = ZZFeatureMap(\n    feature_dimension=N_QUBITS,\n    reps=2, entanglement="linear"\n)\nquantum_kernel = FidelityQuantumKernel(feature_map=feature_map)\nqsvc = QSVC(quantum_kernel=quantum_kernel)'} /><p>Decompose and inspect the circuit. Identify feature-dependent rotations, repeated layers, and the entanglement pattern before fitting QSVC.</p><a className="source-link" href="https://qiskit-community.github.io/qiskit-machine-learning/stubs/qiskit_machine_learning.kernels.FidelityQuantumKernel.html" target="_blank" rel="noreferrer">Qiskit FidelityQuantumKernel reference ↗</a></div></section>
      <section className="lab-step"><div className="step-marker"><span>07</span><i /></div><div><span className="content-kicker">TRAIN + EVALUATE</span><h2>Fit QSVC and read the kernel matrix</h2><Code text={'qsvc.fit(X_train_q, y_train)\ny_pred_qsvc = qsvc.predict(X_test_q)\nK_train = quantum_kernel.evaluate(x_vec=X_train_q)'} /><div className="checkpoint"><strong>Checkpoint 4</strong><p>Save both confusion matrices, both accuracy scores, the first 5×5 block of K_train, and the full kernel heatmap.</p></div><a className="source-link" href="https://qiskit-community.github.io/qiskit-machine-learning/stubs/qiskit_machine_learning.algorithms.QSVC.html" target="_blank" rel="noreferrer">Qiskit QSVC reference ↗</a></div></section>
      <section className="lab-step"><div className="step-marker"><span>08</span></div><div><span className="content-kicker">INTERPRETATION</span><h2>Turn model output into an evidence table</h2><div className="results-template"><div><strong>Model</strong><strong>Accuracy</strong><strong>Macro F1</strong><strong>Runtime</strong><strong>Largest error</strong></div><div><span>RBF-SVM</span><span>____</span><span>____</span><span>____</span><span>____</span></div><div><span>QSVC</span><span>____</span><span>____</span><span>____</span><span>____</span></div></div><div className="analysis-prompts"><strong>Before you conclude</strong><ol><li>Which families are confused by both models?</li><li>Is an accuracy difference large enough to matter for this test size?</li><li>What information may have been lost in four-component PCA?</li><li>What did the quantum model cost in runtime and circuit evaluations?</li></ol></div></div></section>
    </div><LabProgress /></div>
    <section className="troubleshooting"><span className="content-kicker">TROUBLESHOOTING</span><h2>Common Colab issues</h2><div><details><summary>No ZIP file is found</summary><p>Run the upload cell again and confirm that the archive appears in the Colab file pane. Keep the file extension .zip.</p></details><details><summary>PCA says n_components is too large</summary><p>Reduce N_QUBITS or increase the number of training samples. PCA components cannot exceed the smaller of the training-sample and post-filter feature counts.</p></details><details><summary>QSVC takes too long</summary><p>Return to 3 classes, 25 samples per class, and 4 qubits. Kernel evaluation grows quickly because many sample pairs require circuit evaluation.</p></details><details><summary>Package imports fail after install</summary><p>Use Runtime → Restart session, then run from the import cell. Do not rerun the package install unless needed.</p></details></div></section>
    <div className="next-stage"><div><strong>Lab complete?</strong><p>Save a copy of your notebook and keep your evidence table.</p></div><a className="button button-primary" href={siteHref("/modules/m1/post-lab")}>Continue to Post-Lab →</a></div>
  </>;
}

export function M1PostLab() {
  return <>
    <section className="content-section first-section"><span className="content-kicker">EXTEND THE EVIDENCE</span><h2>One successful run is the beginning, not the conclusion</h2><p className="lead-text">Change one experimental factor, preserve the baseline, and explain the performance-resource tradeoff. Your goal is a defensible comparison—not the highest number.</p></section>
    <section className="content-section"><span className="content-kicker">CORE ADD-ON EXPERIMENT</span><h2>Choose one controlled investigation</h2><div className="experiment-grid"><article><span>A</span><h3>Feature dimension</h3><p>Compare 4, 6, and 8 qubits while holding classes and sample count fixed.</p><small>Watch: explained variance, runtime, accuracy</small></article><article><span>B</span><h3>Feature map</h3><p>Compare ZZFeatureMap with a PauliFeatureMap configuration.</p><small>Watch: kernel structure, circuit depth, errors</small></article><article><span>C</span><h3>Data scale</h3><p>Compare 15, 25, and 40 samples per family.</p><small>Watch: stability, runtime growth, class metrics</small></article><article><span>D</span><h3>Class complexity</h3><p>Increase from three to four malware families.</p><small>Watch: confusion pairs, macro F1, imbalance</small></article></div><div className="control-rule"><strong>Controlled experiment rule</strong><p>Change only one primary factor at a time. Use RANDOM_STATE = 42 and the same train/test logic so the comparison remains interpretable.</p></div></section>
    <section className="content-section"><span className="content-kicker">ADDITIONAL BASELINES</span><h2>Ask whether the quantum kernel earns its complexity</h2><div className="baseline-cards"><article><h3>Logistic regression</h3><p>A simple linear boundary and an important lower-complexity reference.</p></article><article><h3>Random forest</h3><p>A nonlinear tree ensemble that can expose whether the reduced features are already easy to separate.</p></article><article><h3>RBF-SVM</h3><p>The closest classical kernel comparison and the required baseline for every experiment.</p></article></div></section>
    <section className="content-section"><span className="content-kicker">SUBMISSION</span><h2>Your evidence package</h2><div className="deliverable-grid"><div><span>01</span><strong>Executed notebook</strong><p>All cells, outputs, configuration, and random seed visible.</p></div><div><span>02</span><strong>Results table</strong><p>Accuracy, macro F1, runtime, and per-class errors for each model.</p></div><div><span>03</span><strong>Three figures</strong><p>Two confusion matrices plus one kernel or experiment comparison plot.</p></div><div><span>04</span><strong>500-word analysis</strong><p>Claim, evidence, limitations, resource tradeoff, and next experiment.</p></div></div></section>
    <section className="content-section"><span className="content-kicker">ANALYSIS QUESTIONS</span><h2>Write like a careful security researcher</h2><ol className="prompt-list"><li><span>01</span><p>How did the quantum feature map change similarity structure compared with the RBF kernel?</p></li><li><span>02</span><p>Which malware-family confusion matters most operationally, and why?</p></li><li><span>03</span><p>How much information did PCA preserve? What potentially important behavior did it discard?</p></li><li><span>04</span><p>Did QSVC improve any class-level metric consistently enough to justify its additional computational cost?</p></li><li><span>05</span><p>What evidence would be required before making a claim about quantum advantage?</p></li></ol></section>
    <section className="content-section"><span className="content-kicker">ASSESSMENT RUBRIC</span><h2>20-point rubric</h2><div className="rubric"><div><strong>Reproducibility</strong><span>4</span><p>Configuration, seed, dataset selection, and complete outputs are documented.</p></div><div><strong>Technical correctness</strong><span>5</span><p>Preprocessing, baseline, feature map, kernel, QSVC, and metrics are implemented correctly.</p></div><div><strong>Experimental design</strong><span>4</span><p>One factor is changed while relevant controls are preserved.</p></div><div><strong>Evidence + interpretation</strong><span>5</span><p>Claims match results, class-level errors and resource costs are discussed, and limitations are explicit.</p></div><div><strong>Communication</strong><span>2</span><p>Figures, tables, labels, and writing are clear and professional.</p></div></div></section>
    <section className="hardware-note"><div><span>OPTIONAL ADVANCED EXTENSION</span><h2>Simulator-to-hardware kernel check</h2></div><p>Select only 2-5 samples and compare a few kernel entries on a simulator and an IBM Quantum backend. Full QSVC training is not recommended for a first hardware run because kernel evaluation requires many circuit executions and hardware APIs, queues, and noise conditions change.</p></section>
    <section className="reflection-card"><span className="content-kicker light">FINAL REFLECTION</span><h2>“Where did quantum computation begin in this workflow—and where did it end?”</h2><p>Answer in 150-200 words. Distinguish classical data preparation, quantum state preparation and fidelity estimation, and classical SVM decision-making.</p><a href={siteHref("/modules/m2")}>Preview Module 2 →</a></section>
  </>;
}
