import { ModuleCard } from "./components/ModuleCard";
import { SiteFooter } from "./components/SiteFooter";
import { SiteHeader } from "./components/SiteHeader";
import { modules } from "./data/modules";
import { siteHref } from "./lib/site-path";
export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span /> Quantum-AI Cybersecurity Repository</div><h1>Learn quantum machine learning by <em>defending what matters.</em></h1><p className="hero-lead">Ten research-informed modules connect quantum computing, machine learning, and real cybersecurity challenges through a clear learn-build-extend cycle.</p><div className="hero-actions"><a className="button button-primary" href={siteHref("/modules/m1")}>Begin with malware classification <span>→</span></a><a className="button button-quiet" href={siteHref("/modules")}>Explore all 10 modules</a></div><div className="hero-proof" aria-label="Repository highlights"><div><strong>10</strong><span>authentic modules</span></div><div><strong>30</strong><span>learning stages</span></div><div><strong>0</strong><span>specialized hardware required</span></div></div></div>
    <div className="hero-visual" aria-label="A hybrid quantum-classical malware classification workflow"><div className="visual-label"><span>LIVE WORKFLOW</span><span className="pulse">Simulator first</span></div><div className="workflow-node"><span className="node-number">01</span><div><strong>Malware behavior</strong><small>CAPA features</small></div><span className="node-state">128D</span></div><div className="workflow-line"><span /></div><div className="workflow-node"><span className="node-number">02</span><div><strong>Quantum encoding</strong><small>PCA + ZZFeatureMap</small></div><span className="node-state violet">4q</span></div><div className="circuit-strip" aria-hidden="true"><span className="wire" /><i className="gate">H</i><i className="gate gate-r">RZ</i><i className="control" /><i className="target">⊕</i><span className="wire wire-2" /><i className="gate gate-2">H</i></div><div className="workflow-node result-node"><span className="node-number">03</span><div><strong>Evidence, not hype</strong><small>QSVC vs. classical SVM</small></div><span className="node-state coral">A/B</span></div><div className="visual-footer"><span>Reproducible</span><span>Cloud-accessible</span><span>Student-ready</span></div></div></section>
    <section className="purpose-strip"><p><strong>One repository.</strong> A shared path from emerging Quantum-AI research to classroom-ready cybersecurity learning.</p><div><span>Qiskit</span><span>PennyLane</span><span>Google Colab</span><span>Real datasets</span></div></section>
    <section className="section" id="modules"><div className="section-heading split-heading"><div><span className="section-kicker">THE REPOSITORY</span><h2>Ten challenges. One coherent learning path.</h2></div><p>Start with a complete QSVM malware lab, then explore planned blueprints spanning secure software, networks, trustworthy AI, identity, cryptography, and financial crime.</p></div><div className="module-grid">{modules.map((module) => <ModuleCard module={module} key={module.id} />)}</div><div className="center-action"><a className="text-link" href={siteHref("/modules")}>Compare all modules <span>→</span></a></div></section>
    <section className="learning-section" id="learning-model"><div className="learning-intro"><span className="section-kicker light">AUTHENTIC LEARNING MODEL</span><h2>Prepare. Investigate. Make the evidence defend your conclusion.</h2><p>Every module uses the same three-stage rhythm, reducing setup friction while increasing the depth of inquiry.</p></div><div className="learning-cycle"><article><span className="cycle-number">01</span><div className="cycle-rule" /><small>LEARN</small><h3>Pre-Lab</h3><p>Build the cybersecurity and quantum foundations needed to ask a defensible research question.</p><ul><li>Concept briefings</li><li>Readiness check</li><li>Threat context</li></ul></article><article><span className="cycle-number">02</span><div className="cycle-rule" /><small>BUILD</small><h3>Hands-on Lab</h3><p>Run a cloud workflow, capture evidence, and compare quantum and classical baselines.</p><ul><li>Google Colab</li><li>Guided checkpoints</li><li>Reproducible results</li></ul></article><article><span className="cycle-number">03</span><div className="cycle-rule" /><small>EXTEND</small><h3>Post-Lab</h3><p>Change the experiment, evaluate limitations, and connect results to workforce decisions.</p><ul><li>Open-ended inquiry</li><li>Critical comparison</li><li>Reflection + assessment</li></ul></article></div></section>
    <section className="section audience-section" id="about"><div className="section-heading"><span className="section-kicker">BUILT FOR ADOPTION</span><h2>Advanced enough for research. Structured enough for a first QML course.</h2></div><div className="audience-grid"><article><span>ST</span><h3>For students</h3><p>Concrete cybersecurity problems, visible progress, and honest comparisons make abstract quantum ideas easier to grasp.</p></article><article><span>FA</span><h3>For faculty</h3><p>Reusable modules fit upper-level undergraduate and graduate courses without specialized quantum hardware.</p></article><article><span>WF</span><h3>For the workforce</h3><p>Each module connects experimental skills to roles in cyber defense, DevSecOps, trustworthy AI, forensics, and risk.</p></article></div><div className="collaboration-card"><div><span className="section-kicker">REPOSITORY VISION</span><h3>Research-to-impact, across institutions.</h3></div><p>Led by the University of Central Arkansas in collaboration with the University of Arkansas at Little Rock and Tennessee State University, the repository is designed as an open educational resource for multi-institution learning and computing education research.</p></div></section>
    <section className="cta-section"><div><span className="section-kicker light">MODULE 1 IS READY</span><h2>Your first quantum kernel starts with malware behavior.</h2></div><a className="button button-light" href={siteHref("/modules/m1")}>Open the QSVM module <span>→</span></a></section>
  </main><SiteFooter /></>;
}
